/*
 * BuscarVentasDlg.java
 */
package forms;

import dtos.UsuarioDTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juventino López García - 00000248547
 */
public class BuscarUsuariosDlg extends javax.swing.JDialog {

    private List<UsuarioDTO> usuarios;

    /**
     * Creates new form BuscarVentasDlg
     */
    public BuscarUsuariosDlg(java.awt.Frame parent, boolean modal, List<UsuarioDTO> usuarios) {
        super(parent, modal);
        initComponents();
        this.usuarios = usuarios;
        llenarTablaProductos();
    }

    private void llenarTablaProductos() {
        
            List<UsuarioDTO> listaProductos = usuarios;
            DefaultTableModel modeloTabla = (DefaultTableModel) ventasTabla.getModel();

            if (modeloTabla.getRowCount() > 0) {
                for (int i = modeloTabla.getRowCount() - 1; i > -1; i--) {
                    modeloTabla.removeRow(i);
                }
            }

            if (listaProductos != null) {
                listaProductos.forEach(row -> {
                    Object[] fila = new Object[5];
                    fila[0] = row.getRfc();
                    fila[1] = row.getNombre()+ " " + row.getApellidoPaterno() + " " + row.getApellidoMaterno();
                    fila[2] = row.getPuesto();

                    modeloTabla.addRow(fila);
                });
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ventasTabla = new javax.swing.JTable();
        salirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        ventasTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "rfc", "Nombre", "Fecha de contratación"
            }
        ));
        ventasTabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ventasTabla);

        salirBtn.setText("Salir");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salirBtn)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(salirBtn)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salirBtn;
    private javax.swing.JTable ventasTabla;
    // End of variables declaration//GEN-END:variables
}
